# Generated by Django 3.0.7 on 2020-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='location',
            name='map_url',
            field=models.CharField(max_length=300),
        ),
    ]
